### ISSUE TITLE
product page banner images

### ISSUE THREAD

**Issue by pahosler** [middlestate/equine-advantage#1]
@tompricejr 
can we add banner images that are the same size? I edited to fit the mustang image, but the horse mane image is a different size and so it does not fit the background the same.

I will also look into possibly adding a better way to add, scale, and crop images in the netlify-cms

**Comment by tompricejr** [comment]
![horse2](https://user-images.githubusercontent.com/29488170/66771775-f9b9e180-ee6f-11e9-93e2-966b2e03aabc.png)
![horse1](https://user-images.githubusercontent.com/29488170/66771776-f9b9e180-ee6f-11e9-992d-dc72359bc8fb.png)
![horse4](https://user-images.githubusercontent.com/29488170/66771777-f9b9e180-ee6f-11e9-99ae-aeebea847aa6.png)
![horse5](https://user-images.githubusercontent.com/29488170/66771778-f9b9e180-ee6f-11e9-9815-271c8a5b8d13.png)
![horse3](https://user-images.githubusercontent.com/29488170/66771779-fa527800-ee6f-11e9-8988-5c5a5851321a.png)
![horse6](https://user-images.githubusercontent.com/29488170/66771780-fa527800-ee6f-11e9-9ec4-8013eaa043a7.png)

**Comment by tompricejr** [comment]
@pahosler check these out. Let me know if you think they will work.

**Comment by tompricejr** [comment]
@pahosler we just need to have that black overlay on them like they are on the mockup

**Comment by pahosler** [comment]
thanks! I'll give those a try
